### ISSUE TITLE
Can't continue installing macOS

### ISSUE THREAD

**Issue by parawoka0106** [laobamac/Better_OSX_on_PVE#2]
Thanks for this project,the first part of installing works well.
Bug when it reboot to the second part,the 'Apple' icon didn't appear,instead of a grey background.
![pic](https://img2.imgtp.com/2024/03/09/1Cqym3BK.webp)
macOS Big Sur
What happened?What made this?
Thanks.

I5-12600KF ASUS ROG Z690-A

**Comment by laobamac** [comment]
Already update,please see [#a03fec4](https://github.com/laobamac/PVE-OpenCore/commit/a03fec44c3830ce81d2631005ec961523dbbf43a) and [#90df667](https://github.com/laobamac/PVE-OpenCore/commit/90df667089b3d74aaba4e3d3a09baeec8a7dd165).Reset your nvram and prev-lang.
