### ISSUE TITLE
跑完代码黑屏

### ISSUE THREAD

**Issue by SixGodSGD** [laobamac/Better_OSX_on_PVE#3]
具体情况是，正常装完系统后，最后重启进系统，跑完代码白屏，只有鼠标，键盘的大小写也正常，但是屏幕只有鼠标，也可以动，如果摁了鼠标左键，鼠标也会消失，大小写键灯还是正常亮。晃动鼠标的时候，pve的后台cpu占有率会波动。
![微信图片_20240310154046](https://github.com/laobamac/PVE-OpenCore/assets/109714664/2b3b2e09-0f8d-4520-beab-e74cf05303a7)

**Comment by laobamac** [comment]
[V20240621](https://github.com/laobamac/PVE-OpenCore/releases/tag/V20240621)
