### ISSUE TITLE
主板i440fx 键鼠没法操作 usb没有定制

### ISSUE THREAD

**Issue by qian9008** [laobamac/Better_OSX_on_PVE#4]

**Comment by laobamac** [comment]
修改机型q35-7.2版本再次尝试

**Comment by qian9008** [comment]
> 修改机型q35-7.2版本再次尝试

核显直通需要用i440fx， q35有问题

**Comment by laobamac** [comment]
请问你是直通的USB设备还是控制器？

**Comment by qian9008** [comment]
想直通usb端口 ，已经把键鼠加入pve黑名单，虚拟Windows下可以正常使用。

**Comment by laobamac** [comment]
使用UltraISO或其他工具解压img引导文件，编辑config.plist，禁用VirtualSMC.kext和SMC**.kext，禁用USB*.kext，添加USBInjectAll.kext并勾选Kernel-Quirks-XHCIPortLimit尝试

**Comment by qian9008** [comment]
据说  USBInjectAll.kext 了，XhciPortLimit 在 11.3 以上系统已失效就不要勾选了。

**Comment by laobamac** [comment]
无需怀疑，照做后反馈结果即可。XHCIPORTLIMIT在OpenCore0.9.8以后已经支持到14.x，可以关注下ACDT的更新日志

**Comment by qian9008** [comment]
> 无需怀疑，照做后反馈结果即可。XHCIPORTLIMIT在OpenCore0.9.8以后已经支持到14.x，可以关注下ACDT的更新日志

解决 非常感谢！！！

**Comment by laobamac** [comment]
解决问题是我们机呦共同的快乐😆

**Comment by qian9008** [comment]
> 解决问题是我们机呦共同的快乐😆

对了，你的镜像包太大了，浪费空间和流量，22m那个不能启动，然后我下载22m那个，建立个新img，就能启动，用diskgenius 。那个问题也研究好一会，或者用img工具导入虚拟硬盘。

**Comment by laobamac** [comment]
123盘都是带在线安装镜像的，安装后或者想要用自己的完整包安装可以用release的OpenCore-single.img，下个版本开始我不会再提供带在线安装的版本了，打包太浪费时间。

**Comment by qian9008** [comment]
键盘鼠标有效果，但是usb3的设备发现不了了。我改了下端口配置usb3有反应，键鼠又没用了。感觉还是要特殊定制

**Comment by laobamac** [comment]
i440fx未经过特殊适配，可能会存在问题。我的建议是增加GenericUSBXHCI.kext尝试，并直接直通USB控制器，而不是使用映射USB设备。
