### ISSUE TITLE
请问支持intel GVT-g 驱动核显的方式吗？

### ISSUE THREAD

**Issue by devchenli** [laobamac/Better_OSX_on_PVE#6]
硬件：intel 8569U ，lris plus 655 核显。
目前在PVE上装了windows，已用GVT-g方式驱动核显，效果还不错，比核显直通更方便，所以准备在Mac上试试，搜索到了这个项目，请问是否支持GVT-g方式驱动核显呢？谢谢！

**Comment by laobamac** [comment]
不可以的，macOS下能识别到显卡并加载fb，但是没有任何接口可供输出，且加速并不完整。只可直通整个核显设备

**Comment by devchenli** [comment]
> 不可以的，macOS下能识别到显卡并加载fb，但是没有任何接口可供输出，且加速并不完整。只可直通整个核显设备

明白了，感谢！已star
